[versions]
spock = "2.3-groovy-4.0"
groovy = "3.0.23"
junitJupiter = "5.11.3"
junitPlatform = "1.11.3"
lombok = "1.18.36"
assertJ = "3.26.3"
jetbrains-annotations = "26.0.1"
checkstyleTool = "10.18.1"
pmdTool = "7.5.0"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertJ" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
junit-platform-engine = { group = "org.junit.platform", name = "junit-platform-engine", version.ref = "junitPlatform" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }

[plugins]
huskitInternalConvention = { id = "org.huskit.gradle.internal-gradle-convention-plugin" }
gradlePluginPublish = { id = "com.gradle.plugin-publish", version = "1.3.0" }
